name: Alertmanager Delivery

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Get dependencies
      run: |
        go mod download
        go mod verify
        go get -u github.com/onsi/ginkgo/ginkgo
    - name: Test
      run: go test -v ./...

  # see https://github.com/marketplace/actions/build-and-push-docker-images
  build:
    name: build docker images
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      VERSION: v0.0.1

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: houz42/alertmanager-delivery
          tag_with_ref: true
          dockerfile: ./build/Dockerfile
          add_git_labels: true
          push: true
